import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {api,createWorker} from '../server/worker.mjs';
function setup(){const db=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync('drizzle/'+file,'utf8'));return {db,env:{SITE_ADMIN_EMAIL:'owner@example.test',DB:{prepare:sql=>({bind:(...args)=>({first:async()=>db.prepare(sql).get(...args)||null,all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>db.prepare(sql).run(...args)})})}}};}
const req=(who,path,method='GET',body)=>new Request('https://test.site'+path,{method,headers:{...(who?{'oai-authenticated-user-id':who,'oai-authenticated-user-email':who+'@example.test'}:{}),Origin:'https://test.site','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
test('admin APIs deny anonymous and ordinary users, including spoofed body roles',async()=>{const {env}=setup();for(const path of ['/api/admin/workspaces','/api/admin/audit','/api/admin/read']){assert.equal((await api(req(null,path),env)).status,401);assert.equal((await api(req('user',path),env)).status,403);}assert.equal((await api(req('user','/api/admin/read','POST',{isAdmin:true,userId:'owner',reason:'debug'}),env)).status,403);delete env.SITE_ADMIN_EMAIL;assert.equal((await api(req('owner','/api/admin/workspaces'),env)).status,403);});
test('admin reads are scoped, reasoned and audited without modifying project data',async()=>{const {db,env}=setup();const state={schema:3,projects:[{id:'project',nodes:[],edges:[]}]};await api(req('user','/api/workspace','PUT',{revision:0,data:state}),env);const listing=await (await api(req('owner','/api/admin/workspaces'),env)).json();assert.equal(listing.totals.users,1);assert.equal(listing.totals.projects,1);assert.equal(listing.items[0].data,undefined);assert.equal((await api(req('owner','/api/admin/read','POST',{userId:'user',reason:''}),env)).status,400);const result=await (await api(req('owner','/api/admin/read','POST',{userId:'user',reason:'排查节点显示问题'}),env)).json();assert.deepEqual(result.data,state);assert.equal(db.prepare('SELECT reason FROM admin_reads WHERE action = ?').get('read').reason,'排查节点显示问题');assert.equal(db.prepare('SELECT revision FROM workspaces WHERE user_id = ?').get('user').revision,1);assert.equal((await api(req('owner','/api/admin/read','DELETE'),env)).status,405);});
test('admin pagination bounds and direct HTML routes are protected',async()=>{const {env}=setup();assert.equal((await api(req('owner','/api/admin/workspaces?offset=-1'),env)).status,400);const worker=createWorker({'/admin.html':{body:'admin'}});assert.equal((await worker.fetch(req('user','/admin.html'),env)).status,403);assert.equal((await worker.fetch(req(null,'/admin'),env)).status,302);const response=await worker.fetch(req('owner','/admin'),env);assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');});
test('audit failure prevents disclosure of project contents',async()=>{const {env}=setup();env.DB.prepare=()=>({bind:()=>({run:async()=>{throw Error('audit storage unavailable');}})});const worker=createWorker({});const response=await worker.fetch(req('owner','/api/admin/read','POST',{userId:'user',reason:'investigate bug'}),env);assert.equal(response.status,503);assert.equal((await response.json()).error,'storage_unavailable');});
